2020-06-26T15:44:48|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 61, in connect
    K = self.keithley = KeithleySourceMeter(port=self.port.val, debug=self.debug_mode.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 39, in __init__
    self.reset()
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 71, in reset
    self.keithey.send("status:queue:clear;*RST;:stat:pres;:*CLS;")
AttributeError: 'KeithleySourceMeter' object has no attribute 'keithey'

2020-06-26T15:45:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 61, in connect
    K = self.keithley = KeithleySourceMeter(port=self.port.val, debug=self.debug_mode.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 39, in __init__
    self.reset()
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 71, in reset
    self.keithey.send("status:queue:clear;*RST;:stat:pres;:*CLS;")
AttributeError: 'KeithleySourceMeter' object has no attribute 'keithey'

2020-06-26T15:45:52|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 61, in connect
    K = self.keithley = KeithleySourceMeter(port=self.port.val, debug=self.debug_mode.val)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 39, in __init__
    self.reset()
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 71, in reset
    self.keithey.send("status:queue:clear;*RST;:stat:pres;:*CLS;")
AttributeError: 'KeithleySourceMeter' object has no attribute 'keithey'

