2020-07-02T14:34:46|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "..\keithley_sourcemeter\keithley2400_sourcemeter_hc.py", line 78, in connect
    K.write_source_mode(self.SOURCE_MODE_DEFAULT)
AttributeError: 'Keithley2400SourceMeter' object has no attribute 'write_source_mode'

