2020-06-25T10:32:14|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 181, in read_from_hardware
    lq.read_from_hardware()
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\logged_quantity.py", line 161, in read_from_hardware
    val = self.hardware_read_func()
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 81, in <lambda>
    self.source_V_a_range.connect_to_hardware(lambda:self.read_range('SOUR', 'VOLT'), None)
  File "..\keithley_sourcemeter\keithley_sourcemeter_hc.py", line 121, in read_range
    _range = self.keithley.read_range(sour_or_sens, volt_or_curr)
  File "..\keithley_sourcemeter\keithley_sourcemeter_gpib_interface.py", line 82, in read_range
    return float(resp)
ValueError: could not convert string to float: 'KEITHLEY INSTRUMENTS INC.,MODEL 2401,4330688,A01 Aug 25 2011 12:57:43/A02  /V/M\n'

